
import java.awt.event.WindowEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Toppings extends javax.swing.JFrame {

    /**
     * Creates new form Toppings
     */
    public Toppings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        roastAlmond = new javax.swing.JRadioButton();
        chocolate = new javax.swing.JRadioButton();
        cookie = new javax.swing.JRadioButton();
        fudge = new javax.swing.JRadioButton();
        oreo = new javax.swing.JRadioButton();
        peanut = new javax.swing.JRadioButton();
        cream = new javax.swing.JRadioButton();
        caramel = new javax.swing.JRadioButton();
        marshmallows = new javax.swing.JRadioButton();
        sprinkle = new javax.swing.JRadioButton();
        nuts = new javax.swing.JRadioButton();
        fruits = new javax.swing.JRadioButton();
        pie = new javax.swing.JRadioButton();
        cereal = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 247, 246));

        roastAlmond.setBackground(new java.awt.Color(248, 237, 235));
        roastAlmond.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        roastAlmond.setForeground(new java.awt.Color(51, 0, 102));
        roastAlmond.setText("Roasted Almonds");
        roastAlmond.setBorder(null);

        chocolate.setBackground(new java.awt.Color(248, 237, 235));
        chocolate.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        chocolate.setForeground(new java.awt.Color(51, 0, 102));
        chocolate.setText("Chocolate");
        chocolate.setBorder(null);

        cookie.setBackground(new java.awt.Color(248, 237, 235));
        cookie.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        cookie.setForeground(new java.awt.Color(51, 0, 102));
        cookie.setText("Cookie");
        cookie.setBorder(null);
        cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieActionPerformed(evt);
            }
        });

        fudge.setBackground(new java.awt.Color(248, 237, 235));
        fudge.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        fudge.setForeground(new java.awt.Color(51, 0, 102));
        fudge.setText("Hot Fudge");
        fudge.setBorder(null);

        oreo.setBackground(new java.awt.Color(248, 237, 235));
        oreo.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        oreo.setForeground(new java.awt.Color(51, 0, 102));
        oreo.setText("Oreo");
        oreo.setBorder(null);

        peanut.setBackground(new java.awt.Color(248, 237, 235));
        peanut.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        peanut.setForeground(new java.awt.Color(51, 0, 102));
        peanut.setText("Peanut Butter");
        peanut.setBorder(null);

        cream.setBackground(new java.awt.Color(248, 237, 235));
        cream.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        cream.setForeground(new java.awt.Color(51, 0, 102));
        cream.setText("cream");
        cream.setBorder(null);

        caramel.setBackground(new java.awt.Color(248, 237, 235));
        caramel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        caramel.setForeground(new java.awt.Color(51, 0, 102));
        caramel.setText("Caramel");
        caramel.setBorder(null);

        marshmallows.setBackground(new java.awt.Color(248, 237, 235));
        marshmallows.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        marshmallows.setForeground(new java.awt.Color(51, 0, 102));
        marshmallows.setText("Marshmallows");
        marshmallows.setBorder(null);

        sprinkle.setBackground(new java.awt.Color(248, 237, 235));
        sprinkle.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        sprinkle.setForeground(new java.awt.Color(51, 0, 102));
        sprinkle.setText("Sprinkle");
        sprinkle.setBorder(null);
        sprinkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinkleActionPerformed(evt);
            }
        });

        nuts.setBackground(new java.awt.Color(248, 237, 235));
        nuts.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        nuts.setForeground(new java.awt.Color(51, 0, 102));
        nuts.setText("Nuts");
        nuts.setBorder(null);
        nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsActionPerformed(evt);
            }
        });

        fruits.setBackground(new java.awt.Color(248, 237, 235));
        fruits.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        fruits.setForeground(new java.awt.Color(51, 0, 102));
        fruits.setText("Fruits");
        fruits.setBorder(null);
        fruits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitsActionPerformed(evt);
            }
        });

        pie.setBackground(new java.awt.Color(248, 237, 235));
        pie.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pie.setForeground(new java.awt.Color(51, 0, 102));
        pie.setText("Pie Chips");
        pie.setBorder(null);
        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });

        cereal.setBackground(new java.awt.Color(248, 237, 235));
        cereal.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        cereal.setForeground(new java.awt.Color(51, 0, 102));
        cereal.setText("Cereal");
        cereal.setBorder(null);
        cereal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marshmallows)
                            .addComponent(peanut)
                            .addComponent(fudge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprinkle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cream, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chocolate)
                            .addComponent(roastAlmond))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cookie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caramel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fruits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cereal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pie)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roastAlmond)
                    .addComponent(cookie)
                    .addComponent(nuts))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruits)
                    .addComponent(caramel)
                    .addComponent(chocolate))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pie)
                    .addComponent(cream)
                    .addComponent(peanut))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cereal)
                    .addComponent(oreo)
                    .addComponent(fudge))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprinkle)
                    .addComponent(marshmallows))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 237, 235));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(248, 237, 235));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 0));

        save.setBackground(new java.awt.Color(239, 247, 246));
        save.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(51, 0, 102));
        save.setText("SAVE");
        save.setBorder(null);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\bg.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jPanel4.setBackground(new java.awt.Color(248, 237, 235));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("TOPPINGS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cookieActionPerformed

    private void sprinkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprinkleActionPerformed

    private void nutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutsActionPerformed

    private void fruitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruitsActionPerformed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pieActionPerformed

    private void cerealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerealActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    int scoops = 0;
        
        if(roastAlmond.isSelected()){    scoops = scoops + 1;     }
        if(chocolate.isSelected()){ scoops = scoops +1;      }
        if(fudge.isSelected()){    scoops = scoops +1;      }
        if(marshmallows.isSelected()){  scoops = scoops +1;     }
        if(cookie.isSelected()){  scoops = scoops +1;     }
        if(cream.isSelected()){   scoops = scoops +1;     }
        if(caramel.isSelected()){  scoops = scoops +1;     }
        if(nuts.isSelected()){  scoops = scoops +1;     }
        if(sprinkle.isSelected()){  scoops = scoops +1;     }
        if(fruits.isSelected()){  scoops = scoops +1;     }
        if(pie.isSelected()){  scoops = scoops +1;     }
        if(oreo.isSelected()){  scoops = scoops +1;     }
        if(cereal.isSelected()){  scoops = scoops +1;     }
        if(peanut.isSelected()){  scoops = scoops +1;     }
              
        if (scoops >= 2){         javax.swing.JOptionPane.showMessageDialog(null, "only 1 topping");    }
        else{                     javax.swing.JOptionPane.showMessageDialog(null, "complete order placed! ");        }      
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toppings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toppings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toppings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toppings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toppings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton caramel;
    private javax.swing.JRadioButton cereal;
    private javax.swing.JRadioButton chocolate;
    private javax.swing.JRadioButton cookie;
    private javax.swing.JRadioButton cream;
    private javax.swing.JRadioButton fruits;
    private javax.swing.JRadioButton fudge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton marshmallows;
    private javax.swing.JRadioButton nuts;
    private javax.swing.JRadioButton oreo;
    private javax.swing.JRadioButton peanut;
    private javax.swing.JRadioButton pie;
    private javax.swing.JRadioButton roastAlmond;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton sprinkle;
    // End of variables declaration//GEN-END:variables
}
